version: '3.7'

services:
  postgres:
    image: postgres:alpine
    container_name: pg
    environment:
      POSTGRES_USER: master
      POSTGRES_PASSWORD: Decjapan001
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - 11111:5432
    volumes:
      - ./database:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
